apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageRepositoryBuild
metadata:
  creationTimestamp: "2024-05-20T14:27:37Z"
  name: carvel-repo.garnier.wf
spec:
  export:
    imgpkgBundle:
      image: kind-registry.local:5000/repositories/carvel
