apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: carvel.garnier.wf.1.0.0
spec:
  refName: carvel.garnier.wf
  releasedAt: "2024-05-20T14:26:40Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: kind-registry.local:5000/packages/carvel-demo@sha256:760d802ce8a023aa1be2655e18a2e6bd28b165719df8b04e760880ab72774ed3
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        apps:
          default: []
          description: List of apps that will be created. Each app has a 'name' and
            an 'html' property.
          items:
            additionalProperties: false
            properties:
              html:
                default: ""
                type: string
              name:
                default: ""
                type: string
            type: object
          title: Apps
          type: array
        namespace:
          default: null
          description: Sets the namespace in which to deploy the application. Defaults
            to ''
          nullable: true
          title: Namespace
          type: string
      type: object
  version: 1.0.0
