apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: carvel.garnier.wf
spec:
  displayName: Carvel Demo
  longDescription: A cool app to showcase Carvel at Voxxed Brussels 2024
  shortDescription: VxdBxl Carvel Demo
